version: '3.8'

services:
  forex-ai:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - model_registry:/app/model_registry
      - training_data:/app/training_data
      - checkpoints:/app/training_checkpoints
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_REGISTRY_PATH=/app/model_registry
      - TRAINING_DATA_PATH=/app/training_data
      - CHECKPOINTS_PATH=/app/training_checkpoints
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  model_registry:
  training_data:
  checkpoints:
  redis_data:
  mongodb_data: